<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AyudaDatosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        DB::table('ayuda_datos')->insert([
            // Ayuda 100 x hijo
            [
                'question_slug' => 'nombre_completo',
                'ayuda_id' => 1,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'dni_nie',
                'ayuda_id' => 1,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'iban',
                'ayuda_id' => 1,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'regimen-mutualidad',
                'ayuda_id' => 1,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'operativa-nombre-hijo',
                'ayuda_id' => 1,
                'tipo_dato' => 'hijo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'operativa-fecha-nacimiento-hijo',
                'ayuda_id' => 1,
                'tipo_dato' => 'hijo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nif-hijo',
                'ayuda_id' => 1,
                'tipo_dato' => 'hijo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // IMV
            [
                'question_slug' => 'nombre_completo',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'dni_nie',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'situacion-laboral',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'genero',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nif',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-validez-dni-nie',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero-soporte-nie',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nacionalidad',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grupo-vulnerable',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grupo-vulnerable-convivientes',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grado-discapacidad',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'iban',
                'ayuda_id' => 2,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nombre-conviviente',
                'ayuda_id' => 2,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'dni-nie-conviviente',
                'ayuda_id' => 2,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero-soporte-dni-nie-conviviente',
                'ayuda_id' => 2,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grado-discapacidad-conviviente',
                'ayuda_id' => 2,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-nacimiento-conviviente',
                'ayuda_id' => 2,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nacionalidad-conviviente',
                'ayuda_id' => 2,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'tipo-contrato',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-firma-contrato',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-inicio-contrato',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'precio-inicial-contrato',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'que-incluye-contrato',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'crear-pregunta-metros-cuadrados',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'tipo-via',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nombre-via',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'bloque',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'portal',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'escalera',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'piso',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'puerta',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'codigo-postal',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'provincia',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'municipio',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'referencia-catastral',
                'ayuda_id' => 2,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // BAJ Aragón
            [
                'question_slug' => 'nombre_completo',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nif',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero-soporte-nie',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nacionalidad',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grupo-vulnerable',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grupo-vulnerable-convivientes',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grado-discapacidad',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'iban',
                'ayuda_id' => 17,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nombre-conviviente',
                'ayuda_id' => 17,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'dni-nie-conviviente',
                'ayuda_id' => 17,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero-soporte-dni-nie-conviviente',
                'ayuda_id' => 17,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grado-discapacidad-conviviente',
                'ayuda_id' => 17,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-nacimiento-conviviente',
                'ayuda_id' => 17,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nacionalidad-conviviente',
                'ayuda_id' => 17,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'tipo-contrato',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-firma-contrato',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-inicio-contrato',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'precio-inicial-contrato',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'que-incluye-contrato',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'crear-pregunta-metros-cuadrados',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'tipo-via',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nombre-via',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'bloque',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'portal',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'escalera',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'piso',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'puerta',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'codigo-postal',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'provincia',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'municipio',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'referencia-catastral',
                'ayuda_id' => 17,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // PAV Cataluña -36 años
            [
                'question_slug' => 'nombre_completo',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'estado_civil',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'situacion-laboral',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'genero',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nif',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-validez-dni-nie',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero-soporte-nie',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nacionalidad',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grupo-vulnerable',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grupo-vulnerable-convivientes',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grado-discapacidad',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'iban',
                'ayuda_id' => 5,
                'tipo_dato' => 'solicitante',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nombre-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'dni-nie-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero-soporte-dni-nie-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-validez-dni-nie-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'grado-discapacidad-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-nacimiento-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'genero-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'situacion-laboral-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nacionalidad-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'titular-contrato-conviviente',
                'ayuda_id' => 5,
                'tipo_dato' => 'conviviente',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'tipo-contrato',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-firma-contrato',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'fecha-inicio-contrato',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'precio-inicial-contrato',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'que-incluye-contrato',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'crear-pregunta-metros-cuadrados',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'tipo-via',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'nombre-via',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'numero',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'bloque',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'portal',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'escalera',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'piso',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'puerta',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'codigo-postal',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'provincia',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'municipio',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_slug' => 'referencia-catastral',
                'ayuda_id' => 5,
                'tipo_dato' => 'contrato',
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ]);
    }
}
