<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AyudaAlquilerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ayudas')->insert([

            [
                'nombre_ayuda' => 'Ayuda alquiler general',
                'sector' => 'Vivienda', // Sector general
                'create_time' => now(),
                'questionnaire_id' => 1, // Aquí se pone el ID del cuestionario relacionado, reemplázalo según corresponda
                'presupuesto' => 1000000, // Ejemplo de presupuesto
                'fecha_inicio' => '2025-01-01', // Fecha de inicio de la ayuda
                'fecha_fin' => '2025-12-31', // Fecha de fin de la ayuda
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => null,
                'organo_id' => 20, // ID del organismo emisor, reemplázalo si es necesario
                'activo' => 0, // Estado activo (1 = activo, 0 = inactivo)
                'created_at' => now(),
                'updated_at' => now(),
                'cuantia_usuario' => 6000, // Cuantía de la ayuda por usuario (esto es un ejemplo)
                'slug' => 'ayuda_alquiler_general',
            ],

            // Ayudas de Alquiler Cataluña
            [
                'nombre_ayuda' => 'Bono Alquiler Joven Cataluña',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 3,
                'presupuesto' => 8800000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda de hasta 250€/mes durante 2 años para jóvenes hasta 35 años con alquiler hasta 900€. Se exige empadronamiento, contrato o compromiso de formalización, y justificantes de pago desde enero de 2025. Presentación del 19 al 23 de mayo exclusivamente.',
                'organo_id' => 2,
                'activo' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_cataluna',
            ],

            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Cataluña -36',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 22,
                'presupuesto' => 13400000,
                'fecha_inicio' => '2025-06-30',
                'fecha_fin' => '2025-07-11',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Subvención destinada a jóvenes menores de 36 años con contrato de alquiler o cesión de uso en vigor en Cataluña, para sufragar entre el 20 % y el 40 % del importe del alquiler durante todo 2025. La cuantía depende del esfuerzo económico e ingresos de la unidad de convivencia. El tope por persona es de 3.000 €, sin superar el 75 % del coste total del alquiler si hay varios beneficiarios. Se exige empadronamiento previo, estar al corriente de pagos y cumplir con los topes de ingresos y precio del alquiler',
                'organo_id' => 2,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_cataluna_menos_36',
            ],

            // Ayudas de Alquiler Comunidad Valenciana
            [
                'nombre_ayuda' => 'Bono Alquiler Joven Comunidad Valenciana',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 4,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda al alquiler para jóvenes de hasta 35 años con contrato vigente o en condiciones de firmarlo. Cubre hasta 250€/mes durante 24 meses según zona de alquiler y renta. Compatible con algunas ayudas como IMV, pero no con otras de alquiler. Presentación del 1 al 23 de abril de 2025. Justificación en varios tramos hasta 2027.',
                'organo_id' => 4,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_valencia',
            ],

            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Comunidad Valenciana',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 23,
                'presupuesto' => null,
                'fecha_inicio' => '2025-09-01',
                'fecha_fin' => '2025-10-01',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Ayuda destinada a inquilinos de vivienda o habitación con contrato de mínimo 1 año y empadronamiento previo en la Comunidad Valenciana. La subvención cubre entre el 40 % y el 50 % del alquiler anual de 2025, con un máximo de 900 €/mes subvencionables según zona y perfil.',
                'organo_id' => 4,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 5400,
                'slug' => 'pav_valencia',
            ],

            // Ayudas de Alquiler Canarias
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Canarias',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 24,
                'presupuesto' => 99000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => null,
                'organo_id' => 9,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_canarias',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Canarias',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 5,
                'presupuesto' => 10000000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'Ayuda de hasta 250€/mes durante 2 años para jóvenes de hasta 35 años con contrato de alquiler en Canarias y renta inferior a 25.200€. Requiere padrón, contrato y justificantes de pago desde enero de 2025',
                'organo_id' => 9,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_canarias',
            ],

            // Ayudas de Alquiler La Rioja
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda La Rioja',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 25,
                'presupuesto' => 23200000,
                'fecha_inicio' => '2022-09-24',
                'fecha_fin' => '2025-09-01',
                'fecha_inicio_periodo' => '2022-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'El Plan Estatal de Vivienda busca facilitar el acceso al alquiler y mejorar la situación habitacional de personas vulnerables, jóvenes, mayores o con discapacidad. Incluye ayudas directas para el pago del alquiler, fomento del parque público, accesibilidad y alojamientos alternativos, entre otros programas.',
                'organo_id' => 17,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_rioja',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven La Rioja',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 6,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda mensual de hasta 250€ durante 24 meses para jóvenes de hasta 35 años en La Rioja, destinada a cubrir el alquiler de vivienda o habitación. Requiere empadronamiento, contrato de alquiler y justificación de ingresos. Límite de alquiler de 900€. Incompatible con otras ayudas al alquiler para el mismo objeto.',
                'organo_id' => 17,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_rioja',
            ],
            // Ayudas de Alquiler Extremadura
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Extremadura',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 26,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda destinada a inquilinos con contrato de alquiler de vivienda habitual en Extremadura. La subvención cubre entre el 40 % y el 50 % del alquiler mensual, con un máximo anual de 3.600 € (300 €/mes). Es compatible con el Ingreso Mínimo Vital y se prioriza a personas con ingresos reducidos, familias monoparentales, numerosas, personas con discapacidad y jóvenes extutelados.',
                'organo_id' => 10,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3600,
                'slug' => 'pav_extremadura',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Extremadura',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 7,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda mensual de hasta 250 € durante 2 años para jóvenes menores de 35 años en régimen de alquiler en Extremadura. Se requiere contrato, padrón, acreditación de ingresos y estar empadronado en la vivienda arrendada',
                'organo_id' => 10,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_extremadura',
            ],

            // Ayudas de Alquiler Asturias
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Asturias',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 27,
                'presupuesto' => 200000000,
                'fecha_inicio' => '2025-05-19',
                'fecha_fin' => '2025-05-23',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'Ayuda dirigida a jóvenes de hasta 35 años en Asturias, para subvencionar el alquiler de vivienda habitual. El importe cubre hasta 250 €/mes durante un máximo de 2 años. El alquiler no puede superar 900 €/mes, y el solicitante debe estar empadronado en la vivienda. Se requiere contrato de alquiler vigente, pagos justificados y cumplir con los requisitos de ingresos. Se exige la presentación de formularios normalizados, declaraciones responsables en caso de no haber presentado renta, y documentación adicional si hay propiedad no habitable u otras ayudas al alquiler en curso. También se debe firmar el consentimiento para la verificación de datos.',
                'organo_id' => 15,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_asturias',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Asturias',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 8,
                'presupuesto' => 6600000,
                'fecha_inicio' => '2025-05-19',
                'fecha_fin' => '2025-05-23',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'Ayuda de hasta 250€/mes durante 2 años para jóvenes menores de 35 años en régimen de alquiler en Asturias. Se solicita entre el 19 y el 23 de mayo de 2025 y requiere contrato, empadronamiento e ingresos justificados.',
                'organo_id' => 15,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_asturias',
            ],

            // Ayudas de Alquiler Aragón

            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Aragón',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 28,
                'presupuesto' => 6200000,
                'fecha_inicio' => '2025-07-22',
                'fecha_fin' => '2025-12-31',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Ayuda al alquiler en Aragón para personas con contrato de vivienda o habitación y que estén empadronadas en el domicilio. Cubre hasta el 50 % del alquiler mensual con un máximo de 600 €/mes o 300 €/mes si es por habitación (hasta 900 € para familias numerosas o discapacidad). Se requiere justificación bancaria de pagos, contrato registrado y no se permiten pagos en efectivo. Solo una solicitud por unidad de convivencia, y la concesión se realiza por orden de entrada hasta agotar presupuesto. Es compatible con el IMV y otras ayudas locales, pero incompatible con ayudas estatales de alquiler. Se permite cambio de domicilio si se comunica y se cumplen los requisitos',
                'organo_id' => 11,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 10800,
                'slug' => 'pav_aragon',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Aragón',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 9,
                'presupuesto' => 7600000,
                'fecha_inicio' => '2025-07-08',
                'fecha_fin' => '2025-08-20',
                'fecha_inicio_periodo' => '2024-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Ayuda de hasta 250€/mes durante 24 meses para jóvenes de 18 a 35 años con ingresos inferiores a 25.200€/año. Compatible con alquiler de vivienda o habitación, se concede por orden de solicitud hasta agotar presupuesto.',
                'organo_id' => 11,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_aragon',
            ],

            // Ayudas de Alquiler Castilla y León
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Castilla y León',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 29,
                'presupuesto' => 11000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Subvención dirigida a facilitar el acceso y permanencia en una vivienda en régimen de alquiler a personas con recursos económicos limitados, en el marco del Plan Estatal de Vivienda 2022-2025. Cubre hasta el 50 % del alquiler mensual durante todo 2024, con cuantías mayores para colectivos especiales (discapacidad, familias numerosas, víctimas de violencia, etc.). Ayuda compatible con IMV y ayudas municipales siempre que no se duplique la mensualidad. Incompatible con Bono Alquiler Joven u otras ayudas para el mismo periodo.',
                'organo_id' => 5,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3600,
                'slug' => 'pav_castilla_leon',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Castilla y León',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 10,
                'presupuesto' => 7100000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'Ayuda de 250€/mes durante 2 años para jóvenes de hasta 35 años con contrato de alquiler o cesión, empadronamiento y renta inferior a 25.200€. Se exige pago bancario, no parentesco con el arrendador y empadronamiento en la vivienda desde el inicio del contrato. Se puede solicitar del 12 de junio al 11 de julio de 2024',
                'organo_id' => 5,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_castilla_leon',
            ],

            // Ayudas de Alquiler Castilla-La Mancha
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Castilla-La Mancha',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 30,
                'presupuesto' => 15600000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Subvención dirigida a personas con escasos recursos económicos que residen en Castilla-La Mancha, para facilitar el pago del alquiler o cesión de uso de su vivienda habitual. Cubre el 50% de la renta durante un máximo de 24 meses. Incluye límites ampliados para familias numerosas y personas con discapacidad. Se prioriza el orden de solicitud válida.',
                'organo_id' => 7,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 7200,
                'slug' => 'pav_castilla_lamancha',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Castilla-La Mancha',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 11,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda de hasta 250€/mes durante 2 años para jóvenes de hasta 35 años con contrato de alquiler o cesión, empadronamiento obligatorio y límite de ingresos de 25.200€. Compatible con el IMV y ayudas sociales, requiere justificación bancaria del pago y se tramita telemáticamente en Castilla-La Mancha.',
                'organo_id' => 7,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_castilla_lamancha',
            ],

            // Ayudas de Alquiler Baleares
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Baleares',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 31,
                'presupuesto' => 9200000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Ayuda autonómica al alquiler en Illes Balears, dirigida a inquilinos de vivienda habitual sin límite de edad. Subvenciona hasta el 50 % del alquiler, con un tope de 3.000 € anuales durante 12 meses. El contrato debe tener una duración mínima de un año y el pago debe realizarse a través de entidad financiera. El alquiler no puede superar los 900 €/mes, y todos los convivientes deben cumplir los requisitos de ingresos. Se prioriza por orden de entrada y es incompatible con otras ayudas al alquiler por el mismo concepto',
                'organo_id' => 13,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_baleares',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Baleares',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 12,
                'presupuesto' => 4800000,
                'fecha_inicio' => '2025-06-16',
                'fecha_fin' => '2025-07-16',
                'fecha_inicio_periodo' => '2024-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Ayuda de hasta 250€/mes durante 2 años (máx. 6.000€) para jóvenes menores de 35 años con contrato de alquiler o cesión en vigor, empadronamiento y renta inferior a 25.200€. Se puede solicitar del 16 de junio al 16 de julio de 2025, y requiere justificación de pagos y documentación laboral.',
                'organo_id' => 13,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_baleares',
            ],

            // Ayudas de Alquiler Andalucía
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Andalucía',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 32,
                'presupuesto' => 57000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'Ayuda dirigida a personas en situación de vulnerabilidad acreditada en Andalucía. Cubre parte o la totalidad del alquiler mensual de 2024, hasta un máximo de 375 €/mes. El plazo de solicitud es del 5 de julio al 5 de agosto de 2024, y solo se concede si se justifica una situación de vulnerabilidad recogida en las bases. Es compatible con otras ayudas siempre que no se superen los límites establecidos ni se duplique el objeto subvencionado. Se debe tramitar preferentemente de forma telemática.',
                'organo_id' => 1,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 4500,
                'slug' => 'pav_andalucia',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Andalucía',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 13,
                'presupuesto' => 34200000,
                'fecha_inicio' => '2025-01-14',
                'fecha_fin' => '2025-06-30',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2027-01-31',
                'description' => null,
                'organo_id' => 1,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_andalucia',
            ],

            // Ayudas de Alquiler Murcia

            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Murcia',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 33,
                'presupuesto' => 5000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => ' Ayuda estatal gestionada por la Región de Murcia destinada a facilitar el pago del alquiler a personas con dificultades económicas. Subvenciona entre el 50 % y el 60 % del alquiler mensual durante 2025, con un tope de 600 € (o 900 € en zonas tensionadas). Requiere contrato, empadronamiento, estar al corriente de pagos y cumplir límites de ingresos. Compatible con IMV; incompatible con otras ayudas estatales de alquiler. Se otorga por orden de entrada.',
                'organo_id' => 12,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 10800,
                'slug' => 'pav_murcia',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Murcia',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 14,
                'presupuesto' => 5000000,
                'fecha_inicio' => '2025-04-13',
                'fecha_fin' => '2025-06-13',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'Subvención de hasta 250€/mes durante 24 meses para jóvenes de 18 a 35 años con contrato de alquiler o cesión. Compatible con otras ayudas si no se solapan. Requiere empadronamiento y justificantes de pago por vías rastreables. Límite de renta: 600€ (vivienda) / 300€ (habitación)',
                'organo_id' => 12,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_murcia',
            ],

            // Ayudas de Alquiler Madrid
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Madrid',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 34,
                'presupuesto' => 21500000,
                'fecha_inicio' => '2025-11-01',
                'fecha_fin' => '2025-12-15',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Ayuda dirigida a personas con escasos recursos económicos que residen en Madrid. Cubre el 50 % del alquiler mensual de 2025, con un máximo de 3.000 €/mes. El plazo de solicitud es del 1 de noviembre al 15 de diciembre de 2025, y solo se concede si se justifica una situación de vulnerabilidad recogida en las bases. Es compatible con otras ayudas siempre que no se superen los límites establecidos ni se duplique el objeto subvencionado. Se debe tramitar preferentemente de forma telemática.',
                'organo_id' => 3,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_madrid',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Madrid',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 15,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda mensual de hasta 250€ durante 24 meses para jóvenes hasta 35 años. Compatible entre convivientes sin parentesco. Se permite solicitar sin contrato firmado aún. Límite de alquiler de 900€ (o 600€ fuera de zona tensionada). No se subvencionan anejos ni gastos extra (se descuentan)',
                'organo_id' => 3,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_madrid',
            ],

            // Ayudas de Alquiler Cantabria
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Cantabria',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 35,
                'presupuesto' => null,
                'fecha_inicio' => '2025-01-23',
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2030-12-31',
                'description' => 'El programa tiene como finalidad facilitar una solución habitacional inmediata a las personas víctimas de violencia de género, víctimas de trata con fines de explotación sexual, víctimas de violencia sexual, personas objeto de desahucio de su vivienda habitual, personas sin hogar y a otras personas especialmente vulnerables, mediante el otorgamiento de una ayuda económica.',
                'organo_id' => 14,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_cantabria',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Cantabria',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 16,
                'presupuesto' => 7600000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'Ayuda de hasta 250€/mes durante 2 años para jóvenes menores de 35 años con contrato de alquiler y renta inferior a 25.200€. Requiere empadronamiento en la vivienda y justificantes de pago desde enero de 2025',
                'organo_id' => 14,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_cantabria',
            ],

            // Ayudas de Alquiler Galicia
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Galicia',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 36,
                'presupuesto' => 20000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Ayuda destinada a inquilinos con contrato mínimo de 1 año y empadronamiento previo en Galicia. La subvención cubre entre el 30 % y el 50 % del alquiler anual, con un tope de 600 €/mes subvencionables según zona. Se otorga durante 2024 y 2025, hasta un máximo de 4.320 € al año, en dos pagos tras justificar los recibos.',
                'organo_id' => 6,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 4320,
                'slug' => 'pav_galicia',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Galicia',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 17,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'Subvención de hasta 250€/mes para jóvenes de hasta 35 años con contrato de alquiler o compromiso de firmarlo. Compatible con IMV y otras prestaciones no contributivas. Incompatible con otras ayudas para el mismo alquiler. El límite del alquiler varía según el municipio (entre 400€ y 700€). Se valoran las solicitudes por orden de entrada y se requiere que estén completas desde el inicio. Ayuda válida desde enero de 2025 hasta diciembre de 2026',
                'organo_id' => 6,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_galicia',
            ],

            // Ayudas de Alquiler País Vasco
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda País Vasco',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 37,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => null,
                'organo_id' => 8,
                'activo' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_pais_vasco',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven País Vasco',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 18,
                'presupuesto' => 50000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => 'El Programa Emantzipa se establece como un programa subvencional consistente en el pago de una cuantía mensual destinada a favorecer el inicio o consolidación de procesos de emancipación de personas jóvenes.',
                'organo_id' => 8,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 7200,
                'slug' => 'baj_pais_vasco',
            ],

            // Ayudas de Alquiler Ceuta
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Ceuta',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 38,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => null,
                'organo_id' => 18,
                'activo' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_ceuta',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Ceuta',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 19,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => null,
                'organo_id' => 18,
                'activo' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_ceuta',
            ],

            // Ayudas de Alquiler Melilla
            [
                'nombre_ayuda' => 'Programa Estatal de Vivienda Melilla',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 39,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => null,
                'organo_id' => 19,
                'activo' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 3000,
                'slug' => 'pav_melilla',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Melilla',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 20,
                'presupuesto' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => null,
                'fecha_fin_periodo' => null,
                'description' => null,
                'organo_id' => 19,
                'activo' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_melilla',
            ],

            // Ayudas de Alquiler Navarra
            [
                'nombre_ayuda' => 'David Navarra',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 40,
                'presupuesto' => null,
                'fecha_inicio' => '2025-01-01',
                'fecha_fin' => '2025-12-31',
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2025-12-31',
                'description' => 'Ayuda dirigida a personas con ingresos bajos que alquilan una vivienda en Navarra como residencia habitual. Subvenciona hasta el 50 % del alquiler mensual, con un máximo de 340 €/mes según nivel de ingresos. La ayuda es indefinida y se renueva anualmente. Es necesario estar inscrito en el Censo de Solicitantes de Vivienda Protegida y no superar 1,7 veces el índice SARA.',
                'organo_id' => 16,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 4080,
                'slug' => 'pav_navarra',
            ],

            [
                'nombre_ayuda' => 'Bono Alquiler Joven Navarra',
                'sector' => 'vivienda',
                'create_time' => null,
                'questionnaire_id' => 21,
                'presupuesto' => 88000000,
                'fecha_inicio' => null,
                'fecha_fin' => null,
                'fecha_inicio_periodo' => '2025-01-01',
                'fecha_fin_periodo' => '2026-12-31',
                'description' => 'La ayuda Emanzipa de Navarra ofrece hasta 250€/mes durante 2 años para jóvenes de entre 23 y 33 años con ingresos entre 3.000€ y 22.000€ (o hasta 33.000€ en UC con más miembros). Requiere contrato de alquiler y pagos demostrables, y solo puede tramitarse mediante certificado digital o Cl@ve.',
                'organo_id' => 16,
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cuantia_usuario' => 6000,
                'slug' => 'baj_navarra',
            ],
        ]);
    }
}
