<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentoSeeder extends Seeder
{
    public function run()
    {
        DB::table('documents')->insert([
            [
                'name' => 'DNI del progenitor',
                'slug' => 'dni-progenitor',
                'por_conviviente' => false,
                'description' => 'DNI del padre o la madre',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'DNI del hijo/a',
                'slug' => 'dni-hijo',
                'por_conviviente' => false,
                'description' => 'DNI de tu hijo o hija',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Firma',
                'slug' => 'firma',
                'por_conviviente' => false,
                'description' => 'Firma usuario',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Declaración Renta 2024',
                'slug' => 'declaracion-renta-2024',
                'por_conviviente' => false,
                'description' => 'Declaración de la renta de 2024',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vida Laboral',
                'slug' => 'vida-laboral',
                'por_conviviente' => false,
                'description' => 'Vida laboral',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Contrato de alquiler',
                'slug' => 'contrato-alquiler',
                'por_conviviente' => false,
                'description' => 'Sube todas las páginas del contrato, incluyendo anexos y firmas. Puede ser un PDF o fotos claras de cada página.',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Justificantes de pago del alquiler',
                'slug' => 'justificantes-pago-alquiler',
                'por_conviviente' => false,
                'description' => 'Justificantes de pago del alquiler',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'mensual',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de titularidad bancaria',
                'slug' => 'certificado-titularidad-bancaria',
                'por_conviviente' => false,
                'description' => 'Certificado de titularidad bancaria',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Padrón colectivo',
                'slug' => 'padron-colectivo',
                'por_conviviente' => false,
                'description' => 'Padrón colectivo',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Documentos especiales',
                'slug' => 'documentos-especiales',
                'por_conviviente' => false,
                'description' => '(certificados de discapacidad, grupos vulnerables ,etc.)',
                'tipo' => 'especial',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Escrituras o Documentos del Registro de la propiedad',
                'slug' => 'escrituras-registro-propiedad',
                'por_conviviente' => false,
                'description' => 'Escrituras o Documentos del Registro de la propiedad',
                'tipo' => 'general',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Documento de identidad convivientes',
                'slug' => 'documento-identidad-convivientes',
                'por_conviviente' => true,
                'description' => 'DNI o NIE del conviviente',
                'tipo' => 'general',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de empadronamiento',
                'slug' => 'certificado-empadronamiento',
                'por_conviviente' => false,
                'description' => 'Certificado de empadronamiento',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Padrón histórico',
                'slug' => 'padron-historico',
                'por_conviviente' => false,
                'description' => 'Padrón colectivo',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Libro de familia o certificado de registro civil',
                'slug' => 'libro-familia-certificado-registro-civil',
                'por_conviviente' => false,
                'description' => '',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Última declaración de la renta del convivientes',
                'slug' => 'ultima-declaracion-renta-convivientes',
                'por_conviviente' => true,
                'description' => '',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sentencia o documento que acredite ser víctima de violencia de género',
                'slug' => 'certificado-violencia-genero',
                'por_conviviente' => true,
                'description' => '',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sentencia o documento que acredite ser trata de seres humanos o explotación sexual',
                'slug' => 'certificado-trata-seres-humanos',
                'por_conviviente' => false,
                'description' => '',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sentencia o documento que acredite haber estado en un centro residencial de protección de menores',
                'slug' => 'certificado-centro-residencial-menores',
                'por_conviviente' => false,
                'description' => '',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de discapacidad',
                'slug' => 'certificado-discapacidad',
                'por_conviviente' => true,
                'description' => 'Documento que acredite tener un grado de discapacidad',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certiciado de servicios sociales personas sin hogar',
                'slug' => 'certificado-personas-sin-hogar',
                'por_conviviente' => false,
                'description' => 'Certificado de servicios sociales que acredite ser persona sin hogar',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
        DB::table('documents')->insert([
            [
                'name' => 'Certificado para víctimas de terrorismo',
                'slug' => 'certificado-victima-terrorismo',
                'por_conviviente' => true,
                'description' => 'Certificado de Ministerio de Interior de España que acredite ser víctima de terrorismo',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de familia numerosa',
                'slug' => 'certificado-familia-numerosa',
                'por_conviviente' => true,
                'description' => 'Certificado que acredite ser familia numerosa generica o especial',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de familia monoparental',
                'slug' => 'certificado-familia-monoparental',
                'por_conviviente' => true,
                'description' => 'Certificado que acredite ser familia monoparental',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de riesgo de exclusión social',
                'slug' => 'certificado-riesgo-exclusion-social',
                'por_conviviente' => false,
                'description' => 'Documento de Servicios Sociales que acredite estar en riesgo de exclusión',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // certificado-exconvicto
            [
                'name' => 'Certificado de exconvicto/a',
                'slug' => 'certificado-exconvicto',
                'por_conviviente' => false,
                'description' => 'Certificado que acredite haber estado en prisión y no haber cometido delitos en los últimos 2 años',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Certificado de joven extutelado',
                'slug' => 'certificado-joven-extutelado',
                'por_conviviente' => true,
                'description' => 'Certificado que acredite haber estado en un centro de protección de menores y no haber cumplido 30 años',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de situación de dependencia',
                'slug' => 'certificado-situacion-dependencia',
                'por_conviviente' => false,
                'description' => 'Certificado que acredite tener una situación de dependencia',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de situación de desempleo',
                'slug' => 'certificado-situacion-desempleo',
                'por_conviviente' => false,
                'description' => 'Certificado que acredite estar en situación de desempleo',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de situación catastrófica',
                'slug' => 'certificado-situacion-catastrofica',
                'por_conviviente' => false,
                'description' => 'Certificado que acredite haber sufrido una situación catastrófica que afecte a la vivienda habitual',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de desahucio o ejecución hipotecaria',
                'slug' => 'certificado-desahucio',
                'por_conviviente' => false,
                'description' => 'Certificado que acredite haber sufrido un desahucio o ejecución hipotecaria en los últimos cinco años',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de dación en pago',
                'slug' => 'certificado-dacion-pago',
                'por_conviviente' => false,
                'description' => 'Certificado que acredite haber realizado una dación en pago de la vivienda habitual en los últimos cinco años',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Informe médico',
                'description' => 'Informe médico, que acredite que has iniciado la semana 21 de embarazo en la fecha de presentación de la solicitud, la edad gestacional, la fecha previsible del parto, número de fetos, firma y número de colegiado del profesional médico.',
                'por_conviviente' => false,
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'tipo' => 'general',
                'slug' => 'informe_medico_gestacion',
            ],
            [
                'name' => 'Certificado de nacimiento',
                'description' => 'Certificado de nacimiento',
                'por_conviviente' => false,
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'slug' => 'certificado_nacimiento',
                'tipo' => 'general',
            ],
        ]);
    }
}
