<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentoSeeder2 extends Seeder
{
    public function run()
    {
        DB::table('documents')->insert([
            [
                'name' => 'Consulta de datos personales',
                'slug' => 'consulta-datos-personales',
                'por_conviviente' => false,
                'description' => 'Consulta de datos personales',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'interno',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Autorización representación',
                'slug' => 'autorizacion-representacion',
                'por_conviviente' => false,
                'description' => 'Autorización para presentación de solicitud de subención',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'interno',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Declaración responsable de ingresos',
                'slug' => 'declaracion-responsable-ingresos',
                'por_conviviente' => false,
                'description' => 'Declaración responsable de ingresos obtenidos por la persona solicitante y/o por las personas que tienen o tendrán su domicilio habitual y permanente en la vivienda arrendada o cedida',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'interno',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nota de localización del Registro de la propiedad',
                'slug' => 'nota-localizacion',
                'por_conviviente' => true,
                'description' => 'Documento informativo que indica en qué Registros de la Propiedad se encuentran inscritas las propiedades de una persona física o jurídica',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Contrato de trabajo o Alta de actividad empresarial(Autónomos)',
                'slug' => 'contrato-trabajo-propia-o-ajena',
                'por_conviviente' => false,
                'description' => 'En caso de ser trabajador por cuenta ajena se debe aportar contrato de trabajo, en caso de ser autónomo aportar Alta de actividad empresarial',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de imputación de rentas',
                'slug' => 'certificado-imputacion',
                'por_conviviente' => false,
                'description' => 'Certificado necesario para personas que no realizaron la renta el año anterior',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado de otra ayuda del alquiler',
                'slug' => 'certificado-ayuda-alquiler-otro-año',
                'por_conviviente' => false,
                'description' => 'Certificado de solicitud de alguna otra ayuda para alquiler en el año actual',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado tributario',
                'slug' => 'certificado-tributario',
                'por_conviviente' => false,
                'description' => 'Documento que proporciona la empresa para la que trabajas o cualquier otra entidad que te haga pagos periódicos. Este certificado detalla cuánto has ganado durante el año y cuánto se ha retenido para pagar tus impuestos de la renta',
                'tipo' => 'general',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Justificante de presentación de ayuda',
                'slug' => 'justificante-presentacion-ayuda',
                'por_conviviente' => false,
                'description' => 'Justificante de presentacion de alguna ayuda tramitada por nosotros',
                'tipo' => 'interno',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nota simple del Registro de la propiedad',
                'slug' => 'nota-simple',
                'por_conviviente' => false,
                'description' => 'Documento informativo que resume la situación jurídica de un inmueble, incluyendo quién es el propietario, si existen cargas (como hipotecas o embargos) y otros detalles relevantes',
                'tipo' => 'general',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Documento acreditativo como hij@ de victima de violencia de genero',
                'slug' => 'hijo-victima-genero',
                'por_conviviente' => false,
                'description' => '',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Justificante de traslado desde otra comunidad autónoma',
                'slug' => 'traslado-desde-otra-ccaa',
                'por_conviviente' => false,
                'description' => 'Documento para demostrar que tu residencia anterior y actual están en diferentes comunidades autónomas y que el traslado es permanente ',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Contrato de personal investigador en formación',
                'slug' => 'contrato-investigador',
                'por_conviviente' => false,
                'description' => 'Contrato laboral que se establece con personas que están realizando su tesis doctoral y que se dedican a tareas de investigación',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado acreditativo de la percepción de prestaciones social pública de caracter periodico, contributiva o asistencial',
                'slug' => 'certificado-percepcion-prestaciones-publicas',
                'por_conviviente' => true,
                'description' => 'Documento emitido por la Seguridad Social que acredita qué prestación se percibe',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Justificante de fuente regular de ingresos',
                'slug' => 'justificante-ingresos-regulares',
                'por_conviviente' => true,
                'description' => 'El justificante de ingresos es un documento que certifica la cantidad de dinero que una persona ha recibido durante un periodo determinado. Este puede ser proporcionado por el banco, tu empleador o cualquier otra entidad que te haga pagos periódicos',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Solicitud de alta de terceros en el sistema de información Económico-Financiera y Logística de la Comunidad Autónoma de Canarias',
                'slug' => 'alta-terceros-canarias',
                'por_conviviente' => false,
                'description' => ' trámite necesario para que una persona física o jurídica pueda recibir pagos por parte de la Administración Pública Canaria',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Documento de identidad',
                'slug' => 'documento_identidad',
                'por_conviviente' => false,
                'description' => 'Por favor, sube una fotografía o imagen de ambas caras de su tu **DNI** o **NIE**',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'general',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Justificación de imposibilidad de habitar vivienda',
                'slug' => 'justificante_imposibilidad_habitar_vivienda',
                'por_conviviente' => false,
                'description' => 'Documento que justifica por qué no puedes habitar la vivienda (divorcio o separacion, Okupación o herencia)',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificación Registral o Nota simple expedida por el Registro de la Propiedad',
                'slug' => 'certificado_registro_propiedad_habitacion',
                'por_conviviente' => false,
                'description' => 'Documento que acredita la propiedad y describe la vivienda, incluyendo el número de habitaciones, emitido por el Registro de la Propiedad.',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado Renta Valenciana de Inclusión',
                'slug' => 'renta_valenciana_inclusion',
                'por_conviviente' => false,
                'description' => 'Documento que acredita ser perceptor de la renta valenciana de inclusión',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado hijo/hija victima de VIOGEN',
                'slug' => 'hijo_viogen',
                'por_conviviente' => false,
                'description' => 'Documento que acredita que su hijo o hija sea victima de VIOGEN',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado victima de violencia sexual',
                'slug' => 'violencia_sexual',
                'por_conviviente' => false,
                'description' => 'Documento que acredita ser victima de violencia sexual ',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Resolución de divorcio o separación',
                'slug' => 'resolucion_divorcio_separacion',
                'por_conviviente' => false,
                'description' => 'Documento que acredita ser divorciado o separado',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'especial',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Anexo',
                'slug' => 'anexo',
                'por_conviviente' => false,
                'description' => 'Documento anexo adicional',
                'allowed_types' => 'application/pdf, image/jpeg, image/png',
                'tipo' => 'interno',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
