<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        DB::table('questions')->insert([
            [
                'slug' => 'nombre_completo',
                'text' => 'Nombre completo',
                'sub_text' => 'Nombre y apellidos completos, sin abreviaturas ni iniciales.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 1,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'dni_nie',
                'text' => 'Nº de documento de identidad',
                'sub_text' => 'Introduce el número de identidad.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 14,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'domicilio',
                'text' => 'Domicilio',
                'sub_text' => null,
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'provincia',
                'text' => '¿En qué provincia vives?',
                'sub_text' => 'Necesitamos esta información para comprobar si puedes acceder a ayudas en tu zona.',
                'type' => 'select',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'municipio',
                'text' => '¿En qué municipio vives?',
                'sub_text' => 'Necesitamos esta información para comprobar si puedes acceder a ayudas en tu zona.',
                'type' => 'select',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'comunidad_autonoma',
                'text' => 'Comunidad Autónoma',
                'sub_text' => 'Necesitamos esta información para comprobar si puedes acceder a ayudas en tu zona.',
                'type' => 'select',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'codigo_postal',
                'text' => 'Código postal',
                'sub_text' => 'Introduce tu código postal de 5 cifras.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 6,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'fecha_nacimiento',
                'text' => 'Fecha de nacimiento',
                'sub_text' => 'Tu edad puede influir en el acceso a algunas ayudas.',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 4,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'estado_civil',
                'text' => 'Estado civil',
                'sub_text' => 'Este dato nos ayuda a calcular tu unidad de convivencia.',
                'type' => 'select',
                'options' => json_encode(['Soltero/a', 'Casado/a', 'Viudo/a', 'Divorciado/a']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'genero',
                'text' => 'Género',
                'sub_text' => null,
                'type' => 'select',
                'options' => json_encode(['Hombre', 'Mujer', 'No binario']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'dinero_ganado',
                'text' => '¿Cuánto dinero ingresaste el año pasado?',
                'sub_text' => 'Indica el total de ingresos anuales brutos obtenidos el año pasado, incluyendo salarios, prestaciones, pensiones...',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 10,
                'exclude_none_option' => false,
                'integer_with_range' => true,
            ],
            [
                'slug' => 'tiene_deudas',
                'text' => '¿Tienes deudas con Hacienda o la Seguridad Social?',
                'sub_text' => "Marca 'Sí' solo si tienes una deuda con Hacienda o con la Seguridad Social que no has reconocido ni estás pagando. Si ya la has reconocido y estás en proceso de pago o acuerdo, marca 'No'.",
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'telefono',
                'text' => 'Teléfono móvil',
                'sub_text' => null,
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 2,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'esta_trabajando',
                'text' => '¿Estás trabajando actualmente?',
                'sub_text' => 'Indica si tienes trabajo actualmente, aunque sea a tiempo parcial.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'tiene_viviendas',
                'text' => '¿Tienes propiedades a tu nombre?',
                'sub_text' => 'Incluye viviendas, terrenos o parte de una propiedad aunque no vivas en ella.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'tiene_hijos_o_pronto',
                'text' => '¿Tienes hijos o vas a tenerlos pronto?',
                'sub_text' => null,
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'nif',
                'text' => 'NIF',
                'sub_text' => 'En el caso de personas físicas suele coincidir con el DNI.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 16,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'corriente_pago',
                'text' => '¿Estás al corriente de pago con Hacienda?',
                'sub_text' => "Marca 'Sí' solo si tienes una deuda con Hacienda que no has reconocido ni estás pagando. Si ya la has reconocido y estás en proceso de pago o acuerdo, marca 'No'.",
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'sin_deudas_ss',
                'text' => '¿Tienes deudas con la Seguridad Social?',
                'sub_text' => " Marca 'Sí' solo si tienes una deuda con la Seguridad Social que no has reconocido ni estás pagando. Si ya la has reconocido y estás en proceso de pago o acuerdo, marca 'No'.",
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'deduccion_maternidad',
                'text' => '¿Aplicas a deducción por maternidad?',
                'sub_text' => 'Esta deducción es compatible con el trabajo y tener hijos menores de 3 años. Se solicita en la declaración de la renta.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'hijos',
                'text' => '¿Cuántos hijos tienes?',
                'sub_text' => null,
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'anterior_ayuda',
                'text' => '¿Has realizado la solicitud de la ayuda de 100€ por hijo al mes por tu hijo o hija ante la agencia Tributaria?',
                'sub_text' => null,
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'otro_hijo_menor3',
                'text' => '¿Has tenido o adoptado un hijo o hija en los últimos 3 años?',
                'sub_text' => 'Si has adoptado, no importa la edad del niño o niña en el momento de la adopción.
                               Lo que cuenta para esta ayuda es la fecha en la que se formalizó la adopción, siempre que haya sido en los últimos 3 años.',
                'type' => 'select',
                'options' => json_encode(['No', 'He tenido un niño/a', 'He adoptado un niño/a']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'is_demandante_empleo',
                'text' => '¿Eres demandante de empleo en el SEPE?',
                'type' => 'boolean',
                'sub_text' => 'Debes estar inscrito como demandante en el SEPE, aunque no estés cobrando el paro.',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'tienePrestaciones',
                'text' => '¿Tienes alguna prestación?',
                'sub_text' => 'Prestaciones como el paro, ingreso mínimo vital, pensión, baja laboral remunerada, etc.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'gradoDiscapacidad',
                'text' => '¿Cuál es tu grado de discapacidad?',
                'sub_text' => 'Selecciona tu grado de discapacidad reconocido oficialmente.',
                'type' => 'select',
                'options' => json_encode(['No tengo discapacidad', 'Superior al 33% e inferior al 65% sin ayuda de terceras personas ni movilidad reducida', 'Superior al 33% e inferior al 65% con ayuda de terceras personas y/o movilidad reducida', 'Superior al 65%', 'Incapacitación judicial por sentencia de la jurisdicción civil']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'metadata_tech',
                'text' => 'Metadatos tech (pregunta interna)',
                'sub_text' => 'PREGUNTA INTERNA PARA EL EQUIPO DE TECH, NO MOSTRAR AL USUARIO',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'tiene_dni',
                'text' => '¿Tienes DNI o NIE?',
                'sub_text' => 'Tienes que tener DNI o NIE para poder solicitar la ayuda.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'edad',
                'text' => '¿Cuántos años tienes?',
                'sub_text' => '¿Cuál es tu edad?',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 22,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'personas_convivencia',
                'text' => '¿Cuántas personas forman tu unidad de convivencia? Contándote a ti.',
                'sub_text' => 'Tu unidad de convivencia es todas aquellas personas que estén empadronadas en el mismo domicilio que tú.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 21,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'numero_menores_convivencia',
                'text' => '¿Cuántos menores de 18 años hay en tu unidad de convivencia?',
                'sub_text' => 'Tu unidad de convivencia es todas aquellas personas que estén empadronadas en el mismo domicilio que tú.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'edad_menor_n1',
                'text' => '¿Cuántos años tiene el menor Nº1?',
                'sub_text' => 'Escriba la edad del menor Nº1.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'edad_menor_n2',
                'text' => '¿Cuántos años tiene el menor Nº2?',
                'sub_text' => 'Escriba la edad del menor Nº2.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'edad_menor_n3',
                'text' => '¿Cuántos años tiene el menor Nº3?',
                'sub_text' => 'Escriba la edad del menor Nº3.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'edad_menor_n4',
                'text' => '¿Cuántos años tiene el menor Nº4?',
                'sub_text' => 'Escriba la edad del menor Nº4.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'edad_menor_n5',
                'text' => '¿Cuántos años tiene el menor Nº5?',
                'sub_text' => 'Escriba la edad del menor Nº5.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'menores_14_convivencia_tienen_dni',
                'text' => '¿Todos los que forman tu unidad de convivencia que sean mayores de 14 años tienen DNI o NIE?',
                'sub_text' => 'Es necesario que los mayores de 14 años dispongan de documento de identidad válido.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'situaciones_imv',
                'text' => '¿Te encuentras en alguna de estas situaciones?',
                'sub_text' => 'Selecciona si te encuentras en alguna de estas situaciones especiales que permiten solicitar el IMV.',
                'type' => 'select',
                'options' => json_encode(['Provienes de centros residenciales de protección de menores, dentro de los 3 años', 'Eres huérfano absoluto', 'Provienes de un centro penitenciario, por tiempo superior a 6 meses', 'Ninguna de las anteriores']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'compartir_domicilio_sin_vinculo',
                'text' => '¿Compartes domicilio con personas con las que no tienes vínculo familiar?',
                'sub_text' => 'Tu primo, tu hermano, tu padre, abuelo, etc. son vínculos familiares.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'has_contrato_habitacion',
                'text' => '¿Tienes un contrato de alquiler de habitación?',
                'sub_text' => '',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'certificado_exclusion_social',
                'text' => '¿Tienes el certificado de servicios sociales que acredite que te encuentras en riesgo de exclusión social?',
                'sub_text' => '',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'personas_convivencia_legal_ininterrumpida_1_anyo',
                'text' => '¿Las personas que forman tu unidad de convivencia han vivido de forma legal e ininterrumpida en España durante más de 1 año?',
                'sub_text' => '',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'motivo_unidad_convivencia_interrumpido_1_anyo',
                'text' => '¿Tu unidad de convivencia no ha vivido de forma legal e ininterrumpida en España durante más de 1 año por alguno de estos motivos?',
                'sub_text' => '',
                'type' => 'select',
                'options' => json_encode(['Eres víctima de violencia de género, trata de seres humanos o explotación sexual', 'Nacimiento, adopción o reagrupación familiar de menores de edad', 'Estancias en el extranjero de menos de 90 días', 'Ausencia por motivos de enfermedad justificada', 'Ninguna de las anteriores']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'vivido_domicilio_diferente_padres_ultimos_dos_anyos',
                'text' => '¿Has vivido en un domicilio diferente al de tus padres, tutores o acogedores durante los últimos dos años?',
                'sub_text' => '',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'trabajado_cotizado_12_meses_ultimos_dos_anyos',
                'text' => '¿Has trabajado y cotizado durante al menos 12 meses en los últimos 2 años?',
                'sub_text' => 'Indica si has cotizado a la Seguridad Social al menos 12 meses en total, dentro de los últimos 2 años.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'situacion_personal',
                'text' => '¿Te encuentras en alguna de estas situaciones?',
                'sub_text' => '',
                'type' => 'select',
                'options' => json_encode(['Fallecimiento de ambos padres', 'Persona sin hogar', 'En trámites de separación o divorcio', 'Persona que acaba de salir de prisión y que tenía una condena superior a 6 meses', 'Víctima de violencia de género, de trata de seres humanos o explotación sexual', 'Ninguna de las anteriores']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'personas_convivencia_ininterrumpida_6_meses',
                'text' => '¿Las personas que forman tu unidad de convivencia han vivido en el mismo domicilio de forma continuada durante los últimos 6 meses?',
                'sub_text' => '',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'motivo_unidad_convivencia_interrupcion_6_meses',
                'text' => '¿Por qué razón tu unidad de convivencia no ha vivido en la misma vivienda durante los últimos seis meses?',
                'sub_text' => '',
                'type' => 'select',
                'options' => json_encode(['Nacimiento, adopción o reagrupación familiar de menores de edad', 'Defunciones', 'Proceso de separación o divorcio', 'Estudios', 'Trabajo', 'Tratamientos médicos o rehabilitación', 'Víctima de violencia de género, trata de seres humanos o explotación sexual', 'Ninguna de las anteriores']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'integrantes_unidad_convivencia_recibe_ayuda_social',
                'text' => 'Alguno de los integrantes de tu unidad de convivencia recibe ayuda por razones de salud o por asistencia social?',
                'sub_text' => '',
                'type' => 'select',
                'options' => json_encode(['Sí, de manera temporal', 'Sí, de manera permanente', 'No']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'unidad_convivencia_hay_admin_empresa',
                'text' => '¿Alguno de tu unidad de convivencia es administrador de una empresa?',
                'sub_text' => '',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'grupo_familiar',
                'text' => '¿Perteneces a alguno de estos grupos?',
                'sub_text' => 'Algunos grupos tienen prioridad: familias monoparentales, personas con discapacidad, etc.',
                'type' => 'select',
                'options' => json_encode(['Algún miembro de la unidad de convivencia tiene una minusvalía superior al 65%', 'Familia monoparental', 'Ninguno de los anteriores']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'valor_bienes_anyo_pasado_sin_casa_vivir',
                'text' => '¿Cuál era, durante el año pasado, el valor total de los bienes o propiedades de todas las personas que forman tu unidad de convivencia, excluyendo la vivienda habitual?',
                'sub_text' => 'Ejemplo: Segundas viviendas, terrenos, vehículos, dinero en cuentas bancarias...',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 19,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'casilla_0012',
                'text' => '¿Cuál fue el ingreso total que obtuviste, o que obtuvieron todas las personas de tu unidad de convivencia, durante el año pasado?',
                'sub_text' => 'Si el resultado es 0 o hay algún valor, ya contamos con la información y no es necesario que rellenes esta pregunta. Si no es así y hiciste la declaración de la renta, puedes fijarte en la casilla 0012',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 19,
                'exclude_none_option' => false,
                'integer_with_range' => true,
            ],
            [
                'slug' => 'retribucion_trabajo',
                'text' => '¿Cuál es la suma de tu última renta en las casillas 03, 07, 08, 09 y 10?',
                'sub_text' => 'Si la suma es 0 o aparece algún valor, ya tenemos la información que necesitamos. En ese caso, NO es necesario que respondas a esta pregunta.',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 19,
                'exclude_none_option' => false,
                'integer_with_range' => true,
            ],
            [
                'slug' => 'base_imponible',
                'text' => '¿Cuál es la suma de tu última renta en las casillas 0435 y 0460?',
                'sub_text' => ' Si ya aparece un valor, no es necesario que rellenes esta pregunta. Base imponible general y base imponible del ahorro',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 19,
                'exclude_none_option' => false,
                'integer_with_range' => true,
            ],
            [
                'slug' => 'iban',
                'text' => '¿Cuál es tu IBAN?',
                'sub_text' => 'Es el número completo de tu cuenta bancaria, empieza por ES y tiene 24 dígitos.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 13,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'ha_trabajado_3_meses_ultimos_6_meses',
                'text' => '¿Has tenido una fuente regular de ingresos en al menos 3 de los últimos 6 meses?',
                'sub_text' => 'Cuenta cualquier fuente regular como contratos, subsidios o pensiones. No importa si no han sido consecutivos.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],
            [
                'slug' => 'fecha_collector',
                'text' => 'PREGUNTA INTERNA. Fecha de realización de Collector',
                'sub_text' => 'PREGUNTA INTERNA. Fecha de realización de Collector',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
                'integer_with_range' => false,
            ],

        ]);
    }
}
