<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder3 extends Seeder
{
    public function run()
    {
        DB::table('questions')->insert([
            [
                'slug' => 'parentesco',
                'text' => 'Parentesco con el solicitante',
                'sub_text' => 'Indica el tipo de relación que tienes con el solicitante principal de la ayuda',
                'type' => 'select',
                'options' => json_encode([
                    'Cónyuge o pareja de hecho',
                    'Hijo/a',
                    'Padre/Madre',
                    'Hermano/a',
                    'Abuelo/a',
                    'Nieto/a',
                    'Tío/a',
                    'Sobrino/a',
                    'Otro familiar',
                    'No familiar (amigo, compañero de piso, etc.)',
                ]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'tipo_documento_identidad',
                'text' => 'Tipo de documento de identidad',
                'sub_text' => 'Selecciona el tipo de documento que utilizas como identificación',
                'type' => 'select',
                'options' => json_encode([
                    'DNI',
                    'NIE',
                    'Pasaporte',
                ]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'fecha_inicio_contrato',
                'text' => 'Fecha de inicio del contrato',
                'sub_text' => 'Indica la fecha en la que comienza el contrato de alquiler',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'fecha_firma_contrato',
                'text' => 'Fecha de firma del contrato',
                'sub_text' => 'Indica la fecha en la que se firmó el contrato',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'fecha_fin_contrato',
                'text' => 'Fecha de finalización del contrato',
                'sub_text' => 'Indica la fecha en la que termina el contrato de alquiler',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'sistema_pago',
                'text' => 'Sistema de pago',
                'sub_text' => 'Selecciona el método con el que pagas el alquiler cada mes',
                'type' => 'select',
                'options' => json_encode([
                    'Bizum',
                    'Transferencia bancaria',
                    'Ingreso a cuenta',
                ]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'referencia_catastral',
                'text' => 'Referencia catastral',
                'sub_text' => 'Introduce la referencia catastral de la vivienda alquilada',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'comarca',
                'text' => 'Comarca',
                'sub_text' => 'Indica la comarca donde se ubica la vivienda. Si no estás seguro, puedes buscarla según tu municipio.',
                'type' => 'string', // tipo string porque se autocompleta
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'contrato_renovado',
                'text' => '¿El contrato ha sido renovado?',
                'sub_text' => 'Indica si has renovado tu contrato de alquiler',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'nacionalidad',
                'text' => 'Nacionalidad',
                'sub_text' => 'Selecciona tu nacionalidad',
                'type' => 'select',
                'options' => json_encode(
                    ['Afgana', 'Albanesa', 'Argelina', 'Andorrana', 'Angoleña', 'Argentina', 'Armenia', 'Australiana', 'Austriaca', 'Azerbaiyana', 'Bahamense', 'Bahreiní', 'Bangladesí', 'Barbadense', 'Bielorrusa', 'Belga', 'Beliceña', 'Beninesa', 'Butanesa', 'Boliviana', 'Bosnia', 'Botsuana', 'Brasileña', 'Británica', 'Bruneana', 'Búlgara', 'Burkinesa', 'Birmana', 'Burundesa', 'Caboverdiana', 'Camboyana', 'Camerunesa', 'Canadiense', 'Centroafricana', 'Chadiana', 'Chilena', 'China', 'Colombiana', 'Comorense', 'Congoleña (Congo-Brazzaville)', 'Congoleña (Congo-Kinshasa)', 'Costarricense', 'Croata', 'Cubana', 'Chipriota', 'Checa', 'Danesa', 'Yibutiana', 'Dominicana', 'Neerlandesa', 'Timorense', 'Ecuatoriana', 'Egipcia', 'Emiratí', 'Ecuatoguineana', 'Eritrea', 'Estonia', 'Suazi', 'Etíope', 'Fiyiana', 'Finlandesa', 'Francesa', 'Gabonesa', 'Gambiana', 'Georgiana', 'Alemana', 'Ghanesa', 'Griega', 'Granadina', 'Guatemalteca', 'Guineana', 'Guineana-Bisáu', 'Guyanesa', 'Haitiana', 'Hondureña', 'Húngara', 'Islandesa', 'India', 'Indonesia', 'Iraní', 'Iraquí', 'Irlandesa', 'Israelí', 'Italiana', 'Marfileña', 'Jamaiquina', 'Japonesa', 'Jordana', 'Kazaja', 'Keniata', 'Kiribatiana', 'Kuwaití', 'Kirguís', 'Laosiana', 'Letona', 'Libanesa', 'Liberiana', 'Libia', 'Liechtensteiniana', 'Lituana', 'Luxemburguesa', 'Malgache', 'Malauí', 'Malaya', 'Maldiva', 'Maliense', 'Maltesa', 'Marshalés', 'Mauritana', 'Mauriciana', 'Mexicana', 'Micronesia', 'Moldava', 'Monegasca', 'Mongola', 'Montenegrina', 'Marroquí', 'Mozambiqueña', 'Namibia', 'Nauruana', 'Nepalesa', 'Neozelandesa', 'Nicaragüense', 'Nigerina', 'Nigeriana', 'Norcoreana', 'Macedonia del Norte', 'Noruega', 'Omaní', 'Pakistaní', 'Palaos', 'Palestina', 'Panameña', 'Papú', 'Paraguaya', 'Peruana', 'Filipina', 'Polaca', 'Portuguesa', 'Catarí', 'Rumana', 'Rusa', 'Ruandesa', 'Santa Lucía', 'Salvadoreña', 'Samoana', 'Sanmarinense', 'Santomense', 'Saudí', 'Senegalesa', 'Serbia', 'Seychellense', 'Sierraleonesa', 'Singapurense', 'Eslovaca', 'Eslovena', 'Salomonense', 'Somalí', 'Sudafricana', 'Surcoreana', 'Sursudanesa', 'Española', 'Sri Lanka', 'Sudanesa', 'Surinamesa', 'Swazilandesa', 'Sueca', 'Suiza', 'Siria', 'Taiwanesa', 'Tayika', 'Tanzana', 'Tailandesa', 'Togolesa', 'Tongana', 'Trinitense', 'Tunecina', 'Turca', 'Turkmena', 'Tuvaluana', 'Ugandesa', 'Ucraniana', 'Uruguaya', 'Uzbeca', 'Vanuatuense', 'Vaticana', 'Venezolana', 'Vietnamita', 'Yemení', 'Zambiana', 'Zimbabuense']
                ),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'nacionalidad_obtenida_3_ultimos',
                'text' => '¿Has obtenido la nacionalidad española en los últimos 3 años?',
                'sub_text' => 'Marca “Sí” solo si obtuviste la nacionalidad española por residencia, opción u otro procedimiento en los últimos 3 años.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'numero_nie',
                'text' => 'Introduce el número de NIE',
                'sub_text' => 'Asegúrate de introducirlo tal como aparece en tu documento, con la letra inicial, los números y la letra final si aplica.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 12,
                'exclude_none_option' => false,
            ],

            [
                'slug' => 'precio_actual_alquiler',
                'text' => 'Precio actual del alquiler',
                'sub_text' => 'Indica el importe mensual actual que pagas por la vivienda.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15, // Asumiendo que es para campos numéricos tipo precio
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'precio_vivienda',
                'text' => 'Precio de la vivienda',
                'sub_text' => 'Indica el precio del alquiler que aparece en el contrato.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'precio_inicial_alquiler',
                'text' => 'Precio inicial del alquiler',
                'sub_text' => '¿Cuánto pagabas al inicio del contrato?',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'precio_garaje',
                'text' => 'Precio del garaje',
                'sub_text' => 'Si pagas garaje aparte, indícalo aquí.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'precio_trastero',
                'text' => 'Precio del trastero',
                'sub_text' => 'Si pagas trastero aparte, indícalo aquí.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'precio_comunidad',
                'text' => 'Gastos de comunidad',
                'sub_text' => 'Introduce el importe mensual de comunidad si lo pagas tú.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'precio_otros_gastos',
                'text' => 'Otros gastos asociados',
                'sub_text' => 'Incluye cualquier otro gasto mensual relacionado con el alquiler. Por ejemplo suministros como agua, internet o electricidad',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'isla',
                'text' => 'Isla de residencia',
                'sub_text' => 'Selecciona la isla en la que resides actualmente.',
                'type' => 'select',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'numero_habitaciones',
                'text' => 'Número de habitaciones de la vivienda',
                'sub_text' => 'Cuéntanos cuántas habitaciones tiene la vivienda que alquilas (sin contar baños ni cocina)',
                'type' => 'select',
                'options' => json_encode(['1', '2', '3', '4', '5 o más']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'numero_propietarios_contrato',
                'text' => '¿Cuántos propietarios figuran en el contrato de alquiler?',
                'sub_text' => 'Indica el número total de personas propietarias que aparecen en el contrato (aunque no vivan en la vivienda).',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'tipo_persona',
                'text' => 'Tipo de persona',
                'sub_text' => 'Indica si eres una persona física o jurídica',
                'type' => 'select',
                'options' => json_encode(['Física', 'Jurídica']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'razon_social',
                'text' => 'Razón social',
                'sub_text' => 'Indica la razón social si eres una persona jurídica',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'numero_titulares_contrato',
                'text' => 'Número de titulares del contrato',
                'sub_text' => 'Introduce cuántas personas figuran como titulares en el contrato de alquiler',
                'type' => 'integer',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'numero_soporte_documento',
                'text' => 'Número de soporte del documento de identidad',
                'sub_text' => 'Puedes encontrarlo en el reverso de tu DNI/NIE. Empieza por una letra seguida de 8 números.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 20,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'fecha_validez_documento',
                'text' => 'Fecha de validez del documento de identidad',
                'sub_text' => 'Introduce la fecha de caducidad de tu DNI, NIE o Pasaporte',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'situacion_laboral',
                'text' => 'Situación laboral',
                'sub_text' => 'Selecciona tu situación laboral actual',
                'type' => 'select',
                'options' => json_encode([
                    'Trabajador/a por cuenta ajena',
                    'Trabajador/a por cuenta propia (autónomo)',
                    'Persona desempleada inscrita como demandante de empleo',
                    'Estudiante',
                    'Jubilado/a o pensionista',
                    'Incapacitado/a permanente',
                    'Persona dedicada a cuidados o tareas del hogar',
                    'Otra situación',
                ]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'es_titular_contrato',
                'text' => '¿Es titular del contrato de alquiler?',
                'sub_text' => 'Marca "Sí" si figura como titular en el contrato de alquiler',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'ha_solicitado_otra_ayuda',
                'text' => '¿Has solicitado otra ayuda para el alquiler?',
                'sub_text' => 'Indica si actualmente estás solicitando otra ayuda relacionada con el alquiler de tu vivienda',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'conviviente_ha_solicitado_otra_ayuda',
                'text' => '¿El conviviente ha solicitado otra ayuda para el alquiler?',
                'sub_text' => 'Indica si esta persona ha solicitado otra ayuda relacionada con el alquiler de la vivienda',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'tipo_ayuda_alquiler_solicitada',
                'text' => '¿Qué ayuda se ha solicitado?',
                'sub_text' => 'Selecciona el tipo de ayuda para el alquiler que ha solicitado esta persona',
                'type' => 'select',
                'options' => json_encode([
                    'Bono Alquiler Joven',
                    'Programa Estatal de Vivienda',
                    'Ayuda autonómica',
                    'Ayuda municipal',
                    'Otra',
                ]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'fecha_solicitud_otra_ayuda_solicitada',
                'text' => 'Fecha de solicitud de la ayuda:',
                'sub_text' => 'Indica la fecha en que se presentó la solicitud de la otra ayuda para el alquiler',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'otra_ayuda_concedida',
                'text' => '¿Te concedieron esta ayuda?',
                'sub_text' => 'Indica si te aprobaron la ayuda del alquiler',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'cantidad_concedida_otra_ayuda',
                'text' => '¿Cuánto dinero ya has cobrado de esta ayuda?',
                'sub_text' => 'Indica la cantidad económica que le han pagado en la otra ayuda de alquiler',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 15,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'renta_valenciana_anterior',
                'text' => '¿Ha percibido la Renta Valenciana de Inclusión el año anterior?',
                'sub_text' => 'Indica si durante el año anterior recibiste esta ayuda autonómica',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'oposicion_consulta_datos',
                'text' => '¿Se opone a la consulta de sus datos por parte de la administración?',
                'sub_text' => 'Marcando “Sí” das tu consentimiento para que la administración consulte tus datos',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'residencia-legal-baleares',
                'text' => '¿El conviviente reside legalmente en las Islas Baleares?',
                'sub_text' => 'Marca “Sí” únicamente si tu conviviente tiene residencia legal',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'pertenece-grupo-vulnerable-conviviente',
                'text' => '¿El conviviente pertenece a algún grupo vulnerable?',
                'sub_text' => 'Selecciona “Sí” solo si el conviviente se encuentra en alguno de los grupos vulnerables reconocidos.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'grupo-vulnerable-conviviente',
                'text' => '¿A qué grupo vulnerable pertenece el conviviente?',
                'sub_text' => 'Selecciona el grupo vulnerable que aplica al conviviente',
                'type' => 'multiple',
                'options' => json_encode([
                    'Persona con discapacidad reconocida inferior o igual al 33%',
                    'Persona con discapacidad reconocida superior al 33%',
                    'Familia numerosa',
                    'Familia monoparental',
                    'Familia numerosa especial',
                    'Familia monoparental especial',
                    'He sido desahuciado/a de mi vivienda habitual',
                    'Perdí mi vivienda por una ejecución hipotecaria o porque la entregué al banco en los últimos cinco años.',
                    'He sido afectado/a por una situación catastrófica (inundación, incendio, terremoto, etc.)',
                    'Ninguna de las anteriores',
                    'He sido víctima de violencia de género',
                    'He sido víctima de terrorismo',
                    'Estoy en riesgo de exclusión social',
                    'Soy joven extutelado/a',
                    'He estado en prisión (exconvicto/a)',
                ]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'email-conviviente',
                'text' => 'Correo electrónico del conviviente',
                'sub_text' => 'Indica el correo electrónico del conviviente',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => 3,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'conviviente-empadronado',
                'text' => '¿El conviviente está empadronado en la vivienda?',
                'sub_text' => 'Marca “Sí” solo si esa persona aparece registrada en el padrón municipal en el mismo domicilio que tú.',
                'type' => 'boolean',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'operativa-nombre-hijo',
                'text' => 'Nombre del hijo/a:',
                'sub_text' => 'Introduce el nombre tal como aparece en el DNI o certificado de nacimiento.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'operativa-fecha-nacimiento-hijo',
                'text' => 'Fecha de nacimiento o adopción:',
                'sub_text' => 'Indica la fecha en que nació o fue adoptado tu hijo/a.',
                'type' => 'date',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'nif-hijo',
                'text' => 'NIF del hijo/a:',
                'sub_text' => 'Introduce el NIF si dispone de él. Si no tiene, puedes dejarlo en blanco.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],
            [
                'slug' => 'regimen-mutualidad',
                'text' => 'Régimen de mutualidad:',
                'sub_text' => 'Indica si perteneces o has cotizado a una mutualidad alternativa a la Seguridad Social, como MUFACE o MUGEJU.',
                'type' => 'string',
                'options' => json_encode([]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'regex_id' => null,
                'exclude_none_option' => false,
            ],

        ]);
    }
}
