services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttf_app
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
      - /var/www/public/build
    env_file:
      - .env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
